# Generated by Django 4.0.3 on 2022-03-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numRevies',
            new_name='numReviews',
        ),
    ]
