# Generated by Django 4.0.3 on 2022-04-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_numrevies_product_numreviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingProce',
            new_name='shippingPrice',
        ),
    ]
